### PR TITLE
[6.0.0] add tarball tests

### PR DESCRIPTION
**Pull request by szadam**
This change is [Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/286)

### CODE REVIEW

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/286)* status: all files reviewed, 5 unresolved discussions (waiting on @szadam)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/286#-NDRQOrK42a7uiF0tpHp):*
Tarball tests gha job
___
*[`.github/workflows/ci.yml` line 31 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/286#-NDRR2eoD8tPu_ukpoYd:-NDRR2eoD8tPu_ukpoYe:b3b81d1) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/0faa3cbc7ecd33aedc317b31fbfe40f9f1b8fabc/.github/workflows/ci.yml#L31)):*
> ```YAML
>           sudo apt install libnuma-dev libdaxctl-dev
> 
>     - name: Install test dependencies
> ```

nit: dependency
___
*[`.github/workflows/ci.yml` line 33 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/286#-NDRQaqX1l0bdgCppwO1:-NDRQaqX1l0bdgCppwO2:bl5b3l7) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/0faa3cbc7ecd33aedc317b31fbfe40f9f1b8fabc/.github/workflows/ci.yml#L33)):*
> ```YAML
>     - name: Install test dependencies
>       run: sudo apt install tcl
>     - name: Build TieredMemDB
> ```

nit: Add an extra empty line between these steps.
___
*[`.github/workflows/ci.yml` line 46 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/286#-NDRRi9K0U9tdquqOryg:-NDRRi9K0U9tdquqOryh:b-rixus0) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/0faa3cbc7ecd33aedc317b31fbfe40f9f1b8fabc/.github/workflows/ci.yml#L46)):*
> ```YAML
>           make
> 
>     - name: default tests
> ```

nit: Start with a capital letter for consistency with other step names.
___
*[`.github/workflows/ci.yml` line 49 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/286#-NDRRvMN6WsVMgJb_KsN:-NDRRvMN6WsVMgJb_KsO:b-rixus0) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/0faa3cbc7ecd33aedc317b31fbfe40f9f1b8fabc/.github/workflows/ci.yml#L49)):*
> ```YAML
>       run: make test
> 
>     - name: pmem tests
> ```

nit: Start with a capital letter for consistency with other step names.

**Review by PatKamin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/286)* status: all files reviewed, 6 unresolved discussions (waiting on @szadam)

___
*[`.github/workflows/ci.yml` line 9 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/286#-NDRToqf2dwU5tbBOYlG:-NDRToqf2dwU5tbBOYlH:blgw9rb) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/0faa3cbc7ecd33aedc317b31fbfe40f9f1b8fabc/.github/workflows/ci.yml#L9)):*
> ```YAML
>   test-tarball:
>     runs-on: ubuntu-22.04
>     name: Compiler ${{ matrix.env.cc }}
> ```

Add "Test tarball |" to this name for more accurate workflow naming.

**Comment by szadam** [comment]
*[`.github/workflows/ci.yml` line 31 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/286#-NDRR2eoD8tPu_ukpoYd:-NDR_ThK2GORj0McHvGt:b-w92op0) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/0faa3cbc7ecd33aedc317b31fbfe40f9f1b8fabc/.github/workflows/ci.yml#L31)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

nit: dependency
</blockquote></details>

it isn't necessary step

**Review by szadam — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/286)* status: all files reviewed, 2 unresolved discussions (waiting on @PatKamin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/286#-NDRQOrK42a7uiF0tpHp):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Tarball tests gha job
</blockquote></details>

Done.
___
*[`.github/workflows/ci.yml` line 9 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/286#-NDRToqf2dwU5tbBOYlG:-NDR_MF83SR1l5m-mfsi:b-896fix) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/0faa3cbc7ecd33aedc317b31fbfe40f9f1b8fabc/.github/workflows/ci.yml#L9)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add "Test tarball |" to this name for more accurate workflow naming.
</blockquote></details>

Done.

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/286)* status: all files reviewed, 1 unresolved discussion (waiting on @szadam)

___
*[`.github/workflows/ci.yml` line 32 at r2](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/286#-NDRer0i1bZnvx5MnqJC:-NDRer0j7Xgbfl-3tUXb:bb5x3mf) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/0ef561700b44d07553a8deee1df1a6098fbf77be/.github/workflows/ci.yml#L32)):*
> ```YAML
> 
>     - name: Build TieredMemDB
>       run: make
> ```

Restore this step.



_Code quote:_
```YAML
    - name: Build TieredMemDB
      run: make
```

**Review by szadam — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/286)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[`.github/workflows/ci.yml` line 32 at r2](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/286#-NDRer0i1bZnvx5MnqJC:-NDgDYSt3BMupSEF-tI8:b-896fix) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/0ef561700b44d07553a8deee1df1a6098fbf77be/.github/workflows/ci.yml#L32)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Restore this step.
</blockquote></details>

Done.

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/286)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szadam)

**Pull request merged**
