### PR TITLE
[6.0.12-devel] Add memkind support

### PR DESCRIPTION
**Pull request by szadam**
This change is [Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76)

### CODE REVIEW

**Review by PatKamin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76#-:-NAnLcqR-SaaMavaYHsT:bnfp4nl)* status: 0 of 33 files reviewed, all discussions resolved

**Review by PatKamin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76)* status: 0 of 33 files reviewed, 3 unresolved discussions (waiting on @PatKamin and @szadam)

___
*[`src/config.c` line 1014 at r10](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76#-NAwg-VrCvJnu6uMbbHS:-NAwg-VrCvJnu6uMbbHT:bnptemc) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/91b673f3c244ccf285cab1a32de3bb9f3f07dc54/src/config.c#L1014)):*
> ```C
>         addReplyBulkCString(c,buf);
>         sdsfree(buf);
>         matches++;
> ```

Double check if it's part of the commit.



_Code quote:_
```C
matches++;
```
___
*[`src/zmalloc.c` line 68 at r10](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76#-NAwhpIAAf3Vsi4lRXi5:-NAwhpIAAf3Vsi4lRXi6:b-y8y2sc) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/91b673f3c244ccf285cab1a32de3bb9f3f07dc54/src/zmalloc.c#L68)):*
> ```C
> #define MEMORY_DRAM_PMEM 1
> 
> #if PREFIX_SIZE > 0
> ```

Not part of memkind support.



_Code quote:_
```C
#if PREFIX_SIZE > 0
```
___
*[`src/zmalloc.c` line 71 at r10](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76#-NAwhtzf77Q-LYkkefKz:-NAwhtzf77Q-LYkkefL-:b-y8y2sc) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/91b673f3c244ccf285cab1a32de3bb9f3f07dc54/src/zmalloc.c#L71)):*
> ```C
> #define ASSERT_NO_SIZE_OVERFLOW(sz) assert((sz) + PREFIX_SIZE > (sz))
> #else
> #define ASSERT_NO_SIZE_OVERFLOW(sz)
> ```

Not part of memkind support.



_Code quote:_
```C
#else
#define ASSERT_NO_SIZE_OVERFLOW(sz)
```

**Comment by szadam** [comment]
*[`src/config.c` line 1014 at r10](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76#-NAwg-VrCvJnu6uMbbHS:-NCKtW5xBBjLDFpchUp_:b-x89iyg) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/91b673f3c244ccf285cab1a32de3bb9f3f07dc54/src/config.c#L1014)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Double check if it's part of the commit.
</blockquote></details>

it is part of the commit

**Comment by szadam** [comment]
*[`src/zmalloc.c` line 68 at r10](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76#-NAwhpIAAf3Vsi4lRXi5:-NCKtp96BLArIMlvmYoQ:b-knouyc) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/91b673f3c244ccf285cab1a32de3bb9f3f07dc54/src/zmalloc.c#L68)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Not part of memkind support.
</blockquote></details>

it is in commit

**Comment by szadam** [comment]
*[`src/zmalloc.c` line 71 at r10](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76#-NAwhtzf77Q-LYkkefKz:-NCKuz1i7zrGdzClA4Gk:b-896fix) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/91b673f3c244ccf285cab1a32de3bb9f3f07dc54/src/zmalloc.c#L71)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Not part of memkind support.
</blockquote></details>

Done.

**Review by szadam — COMMENTED** [review]
> Reviewed 1 of 3 files at r13, 10 of 10 files at r14, 1 of 2 files at r15, 1 of 1 files at r17, 1 of 1 files at r18, 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76)* status: 16 of 33 files reviewed, 3 unresolved discussions (waiting on @PatKamin)

**Review by szadam — COMMENTED** [review]
> Reviewed 17 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76)* status: all files reviewed, 3 unresolved discussions (waiting on @PatKamin)

**Review by PatKamin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76)* status: all files reviewed, 2 unresolved discussions (waiting on @szadam)

___
*[`src/config.c` line 1014 at r10](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76#-NAwg-VrCvJnu6uMbbHS:-NCPWFw06VIjPCyRuZmQ:bqf3ude) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/91b673f3c244ccf285cab1a32de3bb9f3f07dc54/src/config.c#L1014)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

it is part of the commit
</blockquote></details>

It's not a part of memkind support. See https://github.com/TieredMemDB/TieredMemDB/blame/6.0.9-devel/src/config.c
Remove this line.
___
*[`src/zmalloc.c` line 68 at r10](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76#-NAwhpIAAf3Vsi4lRXi5:-NCPVo6uC_kMRNoqSyV8:b-qam44f) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/91b673f3c244ccf285cab1a32de3bb9f3f07dc54/src/zmalloc.c#L68)):*
<details><summary><i>Previously, szadam (Adam Szopiński) wrote…</i></summary><blockquote>

it is in commit
</blockquote></details>

It's not part of memkind support. See https://github.com/TieredMemDB/TieredMemDB/blob/6.0.9-devel/src/zmalloc.c
Remove this line.

**Review by szadam — COMMENTED** [review]
> Reviewed 1 of 3 files at r23, 1 of 10 files at r24, 1 of 1 files at r27, 1 of 1 files at r28, 2 of 2 files at r30.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76)* status: 17 of 33 files reviewed, 2 unresolved discussions (waiting on @PatKamin and @szadam)

___
*[`src/config.c` line 1014 at r10](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76#-NAwg-VrCvJnu6uMbbHS:-NC_gSJu3AvNmrwc-uMj:b-aqwy45) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/91b673f3c244ccf285cab1a32de3bb9f3f07dc54/src/config.c#L1014)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

It's not a part of memkind support. See https://github.com/TieredMemDB/TieredMemDB/blame/6.0.9-devel/src/config.c
Remove this line.
</blockquote></details>

okey, done
___
*[`src/zmalloc.c` line 68 at r10](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76#-NAwhpIAAf3Vsi4lRXi5:-NC_gVD5E_zsyh129hRP:b-aqwy45) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/91b673f3c244ccf285cab1a32de3bb9f3f07dc54/src/zmalloc.c#L68)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

It's not part of memkind support. See https://github.com/TieredMemDB/TieredMemDB/blob/6.0.9-devel/src/zmalloc.c
Remove this line.
</blockquote></details>

okey, done

**Review by szadam — COMMENTED** [review]
> Reviewed 1 of 3 files at r43, 10 of 10 files at r44, 1 of 2 files at r45, 1 of 1 files at r47, 1 of 1 files at r48, 2 of 2 files at r50, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76)* status: all files reviewed, 2 unresolved discussions (waiting on @PatKamin)

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 17 of 30 files at r1, 1 of 3 files at r43, 10 of 10 files at r44, 1 of 2 files at r45, 1 of 1 files at r47, 1 of 1 files at r48, 2 of 2 files at r50, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76)* status: all files reviewed, 2 unresolved discussions (waiting on @PatKamin and @szadam)

___
*[`src/config.c` line 1020 at r50](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76#-NCd2hInAynNtyIJTva8:-NCd2hIoBha9h7cy6oy-:b75kzva) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/9f37cc889c4bbbdfa75c04d6f715ddfcc293326f/src/config.c#L1020)):*
> ```C
>         addReplyBulkCString(c,"dram-pmem-ratio");
>         addReplyBulkCString(c,buf);
>         matches++;
> ```

This line should be in the previous code block.



_Code quote:_
```C
matches++;
```

**Review by szadam — COMMENTED** [review]
> Reviewed 1 of 3 files at r53, 10 of 10 files at r54, 1 of 2 files at r55, 1 of 1 files at r57, 1 of 1 files at r58, 2 of 2 files at r60, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76)* status: all files reviewed, 2 unresolved discussions (waiting on @PatKamin)

___
*[`src/config.c` line 1020 at r50](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76#-NCd2hInAynNtyIJTva8:-NCdwUty5y6V3FLG9Hda:b-896fix) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/9f37cc889c4bbbdfa75c04d6f715ddfcc293326f/src/config.c#L1020)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

This line should be in the previous code block.
</blockquote></details>

Done.

**Review by PatKamin — APPROVED** [review]
:lgtm:

> Reviewed 1 of 10 files at r54.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/76#-:-NCe-xGCDAyiRZmiOojp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szadam)

**Pull request merged**
