### PR TITLE
Add instruction how to create a new branch based on Redis

### PR DESCRIPTION
**Pull request by szadam**
This change is [Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @szadam)

___
*[`index.md` line 2 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwjOQ419qIK0-jQK2i:-NKwjOQ419qIK0-jQK2j:bdl450f) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L2)):*
> ```Markdown
> # Table of Contents
> ```

pls update TOC
___
*[`index.md` line 23 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwiCc_CLcse52WE1hL:-NKwiCc_CLcse52WE1hM:b-kluw21) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L23)):*
> ```Markdown
> * Configurable - use simple parameters to configure new features.
> 
> # How to create new branch based on Redis tag branch
> ```

this section should be rather a sub-section of `# TieredMemDB documentation`
___
*[`index.md` line 25 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwiG-N0Q6Tz3Nh2Jlr:-NKwiG-N0Q6Tz3Nh2Jls:b-2bhii1) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L25)):*
> ```Markdown
> # How to create new branch based on Redis tag branch
> 
> New realeases are uploaded to Redis from time to time. In order to make Redis
> ```

please check for misspells (e.g. using grammarly)
___
*[`index.md` line 27 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwiKhQC8eari1ZgPhI:-NKwiKhQC8eari1ZgPhJ:bpmlxb9) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L27)):*
> ```Markdown
> New realeases are uploaded to Redis from time to time. In order to make Redis
> work with pmem, appropriate changes must be made.  It is needed to create
> a new branch on tieredmemdb based on the Redis. This manual will present
> ```

pls spell `TieredMemDB` rather than any other spelling
___
*[`index.md` line 28 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwiQVR9bJUU-EvhQmK:-NKwiQVR9bJUU-EvhQmL:b-43k9s2) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L28)):*
> ```Markdown
> work with pmem, appropriate changes must be made.  It is needed to create
> a new branch on tieredmemdb based on the Redis. This manual will present
> an example based on creating new branch 7.0.5-devel from Redis tag 7.0.5.
> ```

pls add an explicit sentence, that this instruction will be (most likely) done for a new selected tag (most likely on a brand new tag from Redis)
___
*[`index.md` line 35 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwj9iy29hFeMcE1e__:-NKwj9iy29hFeMcE1e_a:blvyod1) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L35)):*
> ```Markdown
> 
>     https://github.com/TieredMemDB/TieredMemDB. 
>     
> ```

pls remove redundant whitespaces
___
*[`index.md` line 53 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwiuzgD0K4GK4UHv0U:-NKwiuzgD0K4GK4UHv0V:bfg1vgf) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L53)):*
> ```Markdown
>     'cherry-pick <commit sha> <commit sha> ….'
> 
> That commits will make Redis work compatible with pmem.
> ```

pls also mention that sometimes, for Redis to work with pmem, some more commits may be required
___
*[`index.md` line 67 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwjDE_C8ZUtV-98bGu:-NKwjDE_C8ZUtV-98bGv:bv831zd) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L67)):*
> ```Markdown
> 
> 9.	You can go to github’s site and create a pull request
> ( https://help.github.com/articles/creating-a-pull-request/ ). After
> ```

this is an MD file, pls format all links and sections properly

hint: here you have a preview of your changes:
https://github.com/szadam/TieredMemDB/blob/gh-pages/index.md

**Review by PatKamin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343)* status: all files reviewed, 13 unresolved discussions (waiting on @szadam)

___
*[`index.md` line 26 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwlFcD-P9gsnDT0-_y:-NKwlFcD-P9gsnDT0-_z:b-beamv2) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L26)):*
> ```Markdown
> 
> New realeases are uploaded to Redis from time to time. In order to make Redis
> work with pmem, appropriate changes must be made.  It is needed to create
> ```

I would remove this sentence. It's out of context. Why is it needed?



_Code quote:_
```Markdown
It is needed to create
```
___
*[`index.md` line 30 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwlSOBBDdMLstMVAyP:-NKwlSOBBDdMLstMVAyQ:b-j3x4hv) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L30)):*
> ```Markdown
> an example based on creating new branch 7.0.5-devel from Redis tag 7.0.5.
> 
> 1. First, administrator should create a new branch on tieredmemdb based on
> ```

TieredMemDB repository
___
*[`index.md` line 31 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwlXEkDqv6yEZaXs6G:-NKwlXEkDqv6yEZaXs6H:b-4u7cgz) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L31)):*
> ```Markdown
> 
> 1. First, administrator should create a new branch on tieredmemdb based on
> clean Redis branch (7.0.5).
> ```

7.0.5 is a tag, not a redis branch.
___
*[`index.md` line 46 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwlqKi32_JbSV3YfQj:-NKwlqKj8LLA76gWx_W4:b-26bdyz) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L46)):*
> ```Markdown
> tieredmemdb branch. You need to use the command:
> 
>     'python3 tmdb-cherry-pick.py tieredmemdb/<branch name>'
> ```

Mentioning a script that I cannot find anywhere is a bad idea.
___
*[`index.md` line 56 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwlxJmAtJPVC1plcNO:-NKwlxJmAtJPVC1plcNP:b-3fnx13) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L56)):*
> ```Markdown
> You will find this pre-made python script on:
> 
>     https://github.com/intel-innersource/applications.benchmarking.benchmark.pmdk-benchmarks-automation/blob/master/utils/tmdb-add-pmem-support.py
> ```

Remove this link.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343)* status: all files reviewed, 13 unresolved discussions (waiting on @PatKamin and @szadam)

___
*[`index.md` line 56 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwlxJmAtJPVC1plcNO:-NKx0tdG-2MEO7OwbaC-:b-3oax6z) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L56)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Remove this link.
</blockquote></details>

heh, I think you're right... we shouldn't have this link here... perhaps we should put our instructions into that repo, instead of here...?

**Review by PatKamin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343)* status: all files reviewed, 13 unresolved discussions (waiting on @lukaszstolarczuk and @szadam)

___
*[`index.md` line 56 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwlxJmAtJPVC1plcNO:-NKx35H6C3tZqcxQCoEF:b-c32shn) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L56)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

heh, I think you're right... we shouldn't have this link here... perhaps we should put our instructions into that repo, instead of here...?
</blockquote></details>

Sounds like a good idea.

**Review by szadam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343)* status: all files reviewed, 13 unresolved discussions (waiting on @lukaszstolarczuk and @PatKamin)

___
*[`index.md` line 25 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwiG-N0Q6Tz3Nh2Jlr:-NKxC2_kEe9Utkm2qBJl:b-7lm05x) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L25)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please check for misspells (e.g. using grammarly)
</blockquote></details>

okey 
___
*[`index.md` line 26 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwlFcD-P9gsnDT0-_y:-NKxBzvT7NmC6Qlt4OGk:b-fp3f7v) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L26)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

I would remove this sentence. It's out of context. Why is it needed?
</blockquote></details>

I will remove it
___
*[`index.md` line 27 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwiKhQC8eari1ZgPhI:-NKxBzeKE0U2oy6xXDtU:b-cu5w1j) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls spell `TieredMemDB` rather than any other spelling
</blockquote></details>

I will change it
___
*[`index.md` line 28 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwiQVR9bJUU-EvhQmK:-NKxBz9pC4D0iSkiIehB:b-cu5w1j) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add an explicit sentence, that this instruction will be (most likely) done for a new selected tag (most likely on a brand new tag from Redis)
</blockquote></details>

I will change it
___
*[`index.md` line 30 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwlSOBBDdMLstMVAyP:-NKxByj_53pMFOiTaQzv:b-cu5w1j) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L30)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

TieredMemDB repository
</blockquote></details>

I will change it
___
*[`index.md` line 31 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwlXEkDqv6yEZaXs6G:-NKxByUl6bd_B3AQEdiM:b-cu5w1j) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L31)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

7.0.5 is a tag, not a redis branch.
</blockquote></details>

I will change it
___
*[`index.md` line 35 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwj9iy29hFeMcE1e__:-NKxBxSXEsAc4psGLP-T:b-2z37u) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L35)):*
> key
I will change it
___
*[`index.md` line 46 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwlqKi32_JbSV3YfQj:-NKxBpsz4Hdca_wUb0YS:b-hd0ty) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L46)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Mentioning a script that I cannot find anywhere is a bad idea.
</blockquote></details>

You are right
___
*[`index.md` line 53 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwiuzgD0K4GK4UHv0U:-NKxBnZ41IyhFb_7K1_y:b-cu5w1j) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L53)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls also mention that sometimes, for Redis to work with pmem, some more commits may be required
</blockquote></details>

I will change it
___
*[`index.md` line 56 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwlxJmAtJPVC1plcNO:-NKxBbAB1ilMrCNe3an8:blducbr) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L56)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Sounds like a good idea.
</blockquote></details>

I agree. I will close this PR.
___
*[`index.md` line 67 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/343#-NKwjDE_C8ZUtV-98bGu:-NKxBhiy-wSHvcAqexNg:bb7m0b9) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/3c1a5ab991f0468474f27959f885e6cdec367036/index.md#L67)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this is an MD file, pls format all links and sections properly

hint: here you have a preview of your changes:
https://github.com/szadam/TieredMemDB/blob/gh-pages/index.md
</blockquote></details>

okey

**Pull request closed without merging**
