### PR TITLE
Add compile and linking security flags that should not affect runtime…

### PR DESCRIPTION
**Pull request by maciekpac**
… performance

- - -
This change is [Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/48)

### CODE REVIEW

**Review by PatKamin — CHANGES_REQUESTED** [review]
Looks OK. The question is, are the perf results good?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/48#-:-NAJW1Oq8Q553CBX1Iwx:bl8goyu)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/48#-NAJVno89JhvVWfnowNF):*
Shorten the commit msg, ie: "Add compile and linking security flags". If you want to add some details, please do so in the body of the commit msg.

**Comment by maciekpac** [comment]
The perf results are 20% slower, this is an unacceptable drop in IOPS:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mpaczoch/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mpaczoch/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



24/PR-29 | 4243066 | 3447761 | 861947 | 4309707 | 0.13 | 0.13 | 0.32 | 0.32 | 0.53 | 0.54 | 1.15 | 1.15 | 15.76 GiB | 124.92 GiB | 12.6
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
121/PR-48 | 3748101 | 2917313 | 729335 | 3646648 | 0.16 | 0.17 | 0.36 | 0.37 | 0.58 | 0.59 | 1.36 | 1.37 | 15.68 GiB | 125.01 GiB | 12.5



</body>

</html>


I will rerun the tests to make sure this is not an issue with our CI.

**Review by maciekpac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/48)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @PatKamin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/48#-NAJVno89JhvVWfnowNF):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Shorten the commit msg, ie: "Add compile and linking security flags". If you want to add some details, please do so in the body of the commit msg.
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
Let me know offline how it goes.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/48#-:-NAJs8991Rdkru-LqYJu:b-9h7fnd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/48)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)

**Pull request merged**
