### PR TITLE
Add link to GitHub repository

### PR DESCRIPTION
**Pull request by bratpiorka**
This change is [Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/4)

### CODE REVIEW

**Review by maciekpac — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

**Review by maciekpac — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/4)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[index.md, line 15 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/4#-MtJyzd12uh2j7FO-vDz:-MtJyzd12uh2j7FO-vE-:btr0dk4) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/25df499e25b5dc2ff794e949f2b9557341d11c37/index.md#L15)):*
> ```Markdown
> TieredMemDB is a Redis branch that fully uses the advantages of DRAM and Intel Optane Persistent Memory (PMEM). It is fully compatible with Redis and supports all its structures and features. The main idea is to use a large PMEM capacity to store user data and DRAM speed for latency-sensitive structures. We also offer the possibility of defining the DRAM to PMEM ratio, which will be automatically monitored and maintained by application. This allows you to fully adapt the utilization of the memory to your hardware configuration.
> 
> The source for TieredMemDB can be found in this [GitHub repository](https://github.com/TieredMemDB/TieredMemDB).
> ```

The source code of TieredMemDB can be found in this [GitHub repository](https://github.com/TieredMemDB/TieredMemDB).

**Review by PatKamin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/4)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

___
*[index.md, line 15 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/4#-MtJyzd12uh2j7FO-vDz:-MtMFGyS6h0uA1DlKWEE:b32v57) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/25df499e25b5dc2ff794e949f2b9557341d11c37/index.md#L15)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

The source code of TieredMemDB can be found in this [GitHub repository](https://github.com/TieredMemDB/TieredMemDB).
</blockquote></details>

+1

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/4)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @maciekpac)

___
*[index.md, line 15 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/4#-MtJyzd12uh2j7FO-vDz:-MtMk3aFCFH8BNVRpfSc:b-896fix) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/e0246d01bafd72e9b181d4ca0d68715cc08df2a4/index.md#L15)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by PatKamin — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/4)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @maciekpac)

___
*[index.md, line 15 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/4#-MtJyzd12uh2j7FO-vDz:-MtMkRys9vPh4H6f64OQ:b-7ex0mf) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/e0246d01bafd72e9b181d4ca0d68715cc08df2a4/index.md#L15)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The source **code** of

**Review by bratpiorka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/4)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @maciekpac and @PatKamin)

___
*[index.md, line 15 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/4#-MtJyzd12uh2j7FO-vDz:-MtMlI7810xWHrb6j_Ny:b-vts7ls) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/e0246d01bafd72e9b181d4ca0d68715cc08df2a4/index.md#L15)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

The source **code** of
</blockquote></details>

sorry, now this is correct

**Review by PatKamin — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/4)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

**Review by maciekpac — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bratpiorka)

**Pull request merged**
